- lib/mini_magick/image/info.rb
Current version of MiniMagic::Image::info#details missed some values in some cases.
`indentify -verbose`
```
Properties:
date:create: 2015-04-08T16:38:10+08:00
date:modify: 2015-04-08T16:38:10+08:00
Background color: white
```
will be 
```ruby
{
"Properties" => {
"date" => "modify: 2015-04-08T16:38:10+08:00" 
}
}
```
But it should be 
```ruby
{
"Properties" => {
"date:create" => "2015-04-08T16:38:10+08:00",
"date:modify" => "2015-04-08T16:38:10+08:00"
},
"Background color" => "white"
}
```
> Improve MiniMagick::Image#details parsing

- mini_magick.gemspec
Hi,
This change ensures that the version encoded in the gemspec is the right one, regardless of the fact that another version maybe installed somewhere else on the system.
> #unshift lib/ instead of #push to the $LOAD_PATH

- lib/mini_magick/tool.rb
Fix a small spelling mistake (mogirfy -> mogrify) in method documentation of the MiniMagick::Tool class
> Fix spelling in documentation

- lib/mini_magick/tool.rb
- spec/lib/mini_magick/tool_spec.rb
These options were available for a very long time, but missing in `gm mogrify -help` output and could not be used. A set union is used to add the missing options so that the options aren't duplicated once a
fixed graphicsmagick version gets released (should be included in 1.3.22).
More information about the problem can be found in issue #264.
> Add undocumented graphicsmagick mogrify options

- .travis.yml
Build has errored on Travis CI.
e.g. https://travis-ci.org/minimagick/minimagick/jobs/103772458
I have two reasons why I think so.
1. [Build fails because package can't be located](https://github.com/travis-ci/travis-ci/issues/5221)
2. [bundle install failing](https://github.com/travis-ci/travis-ci/issues/5239)
Maybe it fixed by this PR.
But I don't know the reason why [JRuby build has errored](https://travis-ci.org/minimagick/minimagick/builds/91565243) :cry: 
Thanks.
> Maintain .travis.yml

- .travis.yml
- README.md
Would you like to support MRI 2.3?
The reasons are as follows.
* Ruby 2.3 is highly compatible with Ruby 2.2
* Pass the testing
Thanks.
> Ruby 2.3 support

- lib/mini_magick/tool.rb
- spec/lib/mini_magick/tool_spec.rb
As discussed in https://github.com/minimagick/minimagick/pull/359#issuecomment-198548873
Example usage:
```ruby
convert = MiniMagick::Tool::Convert.new
convert.call do |stdout, stderr, status|
fail if stderr =~ /geometry/
end
```
Includes test, documentation and example. Please let me know if there's anything you think should be cleaned up.
> MiniMagick::Tools accepts block to handle output

- lib/mini_magick/image/info.rb
It failed on lines with '='-characters in the exif values.
It should only make a key on the part before the '='-character, and the value should be the part after.
> Split exif lines on the first '='-character

- mini_magick.gemspec
Follow up to #388.
This PR will fix a following build error.
```sh
$ bundle exec rake
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x000000018b8278>
/home/travis/build/minimagick/minimagick/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:104:in `define'
/home/travis/build/minimagick/minimagick/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:80:in `initialize'
/home/travis/build/minimagick/minimagick/Rakefile:16:in `new'
/home/travis/build/minimagick/minimagick/Rakefile:16:in `<top (required)>'
/home/travis/build/minimagick/minimagick/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
```
An above error is caused by a combination of Rake and RSpec versions.
:warning: The …
> Fix a build error in Travis CI

- .travis.yml
- spec/lib/mini_magick/image_spec.rb
[Ruby 2.4.0 has been released](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released). Then this Ruby version is available on Travis CI.
http://rubies.travis-ci.org
And, Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Fix the following deprecated warning in Ruby 2.4.0.
`warning: constant ::Fixnum is deprecated`
Thanks.
> Support Ruby 2.4.0

- lib/mini_magick/shell.rb
- spec/lib/mini_magick/shell_spec.rb
The process output is buffered, and the buffer size is limited. The
process will block on writing to stdout when the buffer is full. That's
why we need to read all data from stdout before waiting for the process
to exit.
I noticed the issue with generating a 200K image.
> Read process output before waiting for exit

- lib/mini_magick/image.rb
This will allow for options to be passed to Kernel.open.
My specific usecase is passing ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE to open-uri.
> Add param options to open method

- lib/mini_magick/shell.rb
`POSIX::Spawn.popen4`, like `Open3.popen3`, is susceptible to deadlock when one of the pipes it uses to capture the subprocess’s `stdout` and `stderr` streams fills up.
For example, assume the fixed-size buffer backing `stderr` reaches capacity: the child process will hang when it next attempts to write to `stderr`. If the parent process attempts to consume `stdout`, it will block until the child process writes to `stdout`, which will never happen.
`MiniMagick::Shell#capture_command` attempts to avoid deadlock by reading from the `stdout` and `stderr` pipes created by `popen4` in separate threads. Unfortunately, we’ve observed deadlocks in production on a regular basis (dozens of times a day at most). I imagine Ruby isn’t switching between the reader threads fast enough to keep both …
> Use POSIX::Spawn::Child to avoid deadlocks due to pipe hangs

- spec/spec_helper.rb
as it's not really needed for tests.
> Remove `pry` from spec_helper

- lib/mini_magick/image/info.rb
Fixes
```
$ ruby -cw lib/mini_magick/image/info.rb
lib/mini_magick/image/info.rb:143: warning: character class has duplicated range: /:[\s\n]/
lib/mini_magick/image/info.rb:144: warning: shadowing outer local variable - hash
lib/mini_magick/image/info.rb:144: warning: shadowing outer local variable - key
Syntax OK
```
You can also see the warnings on [Rails CI](https://travis-ci.org/rails/rails/jobs/395634343#L1411-L1413)
Related #422
> Avoid 2.5+ warnings

- spec/lib/mini_magick/image_spec.rb
I want to make our CI green to easily find a PR breaks something or not.
seems we already have a similar PR https://github.com/minimagick/minimagick/pull/454
but it'll break builds against IM 7.
> Fix test for IM 6

- .travis.yml
- install/imagemagick.sh
- spec/lib/mini_magick/shell_spec.rb
To make sure CI is fixed via these two PRs, this PR depends on https://github.com/minimagick/minimagick/pull/464.
Please review and merge https://github.com/minimagick/minimagick/pull/464 first 🙏 
---------
For some reason, the following code will take 0.2 sec on JRuby.
```ruby
require 'timeout'
require 'open3'
before = Time.now
_, _, _, subprocess_thread = Open3.popen3(*%w[sleep 1])
begin
Timeout.timeout(0.1) { subprocess_thread.join }
rescue Timeout::Error
end
p Time.now - before
```
It means a thread runs `sleep` is already finished when MiniMagick kills the process in
https://github.com/minimagick/minimagick/blob/1997088636c0dada0f17f10477aec80727f0cb5e/lib/mini_magick/shell.rb#L68
> [Don't merge] Increase sleep time to fix test for JRuby

- .travis.yml
Ruby 2.6.0 has been released on 2018-12-25. Please add Ruby 2.6 to .travis.yml.
https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
> Test with Ruby 2.6

- .travis.yml
- install/imagemagick.sh
ref: https://github.com/minimagick/minimagick/pull/464
It seems older releases are removed from http://www.imagemagick.org/download/
I thought every version (x.y.z-n) is available on somewhere but I can't
find the page.
According to the following page, every x.y.z-10 should be available but
6.9.10-10 and 7.0.8-10 are not listed.
https://www.imagemagick.org/discourse-server/viewtopic.php?t=12212
So I changed install script to find exact download path.
cc @koic
> Fix download script

- lib/mini_magick/configuration.rb
- lib/mini_magick/image/info.rb
This PR suppresses the following Ruby warnings in production codes.
- ⚠️ `shadowing outer local variable - hash`
- ⚠️ `shadowing outer local variable - key`
- ⚠️ `character class has duplicated range: /:[\s\n]/`
- ⚠️ `method redefined; discarding old processor`
- ⚠️ `method redefined; discarding old processor=`
- ⚠️ `method redefined; discarding old cli`
- ⚠️ `method redefined; discarding old cli=`
- ⚠️ `method redefined; discarding old cli_path`
- ⚠️ `method redefined; discarding old debug=`
- ⚠️ `instance variable @cli not initialized`
- ⚠️ `instance variable @cli_path not initialized`
- ⚠️ `instance variable @processor_path not initialized`
Some warnings are summarized in one commit.
> Suppress deprecation warnings in production code

- .travis.yml
- lib/mini_magick/image.rb
- mini_magick.gemspec
Rails CI with Ruby master has broken by https://github.com/ruby/ruby/pull/2794.
https://buildkite.com/rails/rails/builds/66163#c6c0c423-bb9b-4c20-bab4-8a6aa56c726d/936-1235
https://github.com/rails/rails/blob/5a010d8537afa957f1a6c7ec0d9f4d66ef5ae5e1/activestorage/test/test_helper.rb#L94
To fix the CI failure, fixing kwargs deprecation warnings is required.
> Fix Ruby 2.7 warnings

- install/imagemagick.sh
This pull-request uses XZ archive instead of Gzip on CI.
http://www.imagemagick.org/download/releases/ImageMagick-6.9.10-33.tar.gz is 404 Not Found:  https://travis-ci.org/github/minimagick/minimagick/jobs/661176777
But, https://www.imagemagick.org/download/releases/ImageMagick-6.9.10-33.tar.xz is alive. So this pull-request uses XZ.
And use HTTPS for downloading.
> Fix Imagemagick download URI on CI

- lib/mini_magick/configuration.rb
This pull-request makes no warnings.
Before pull-request: 2 warnings.
```
yuya@yoshiyuki|2:01:27|0% ruby -w -Ilib -rmini_magick -e ''
/home/yuya/src/github.com/minimagick/minimagick/lib/mini_magick/configuration.rb:142: warning: method redefined; discarding old cli
/home/yuya/src/github.com/minimagick/minimagick/lib/mini_magick/configuration.rb:157: warning: method redefined; discarding old cli=
```
After pull-request: no warnings.
```
yuya@yoshiyuki|2:01:48|0% ruby -w -Ilib -rmini_magick -e ''
```
Related old issues and pull-requests:
* https://github.com/minimagick/minimagick/pull/427 https://github.com/minimagick/minimagick/pull/427/commits/2965e55c78e590284a676ab79e67f7185aa4a688
* https://github.com/minimagick/minimagick/issues/422
> Suppress warnings

- README.md
As it was dropped in 1b3fe5928aeb92a4ddade9f89db4ba610ebbef82 (#496)
> Remove Ruby 1.9.3 from README

- lib/mini_magick/image/info.rb
This bug is partly identified by this [Ghostscript thread](https://bugs.ghostscript.com/show_bug.cgi?format=multiple&id=701772), which details that GS may additionally output warning messages when `identify` is run on the associated file. This results in parsing errors, as the output is now multi-line and the file's attributes are read.
The following occurs when MiniMagick attempts to access those attributes:
```bash
wget https://bugs.ghostscript.com/attachment.cgi?id=18348 -O attachment.pdf
```
```ruby
1:(main)> t = MiniMagick::Image.open("attachment.pdf")
=> #<MiniMagick::Image:0x000000000c63b918 ... >
2:(main)> t.dimensions
MiniMagick::Invalid: image data can't be read
from <omitted>/mini_magick.rb:37:in `rescue in cheap_info'
Caused by ArgumentError: invalid value for Integer(): …
```
> Parse out Ghostscript warnings in identfication

- lib/mini_magick/shell.rb
[`Thread#join`](https://ruby-doc.org/core-2.5.0/Thread.html#method-i-join) takes a `timeout` argument, and returns `nil` if the thread hasn't completed in that given time.
It's simpler, cheaper and more reliable than `Timeout.timeout`.
> Simpler command timeout

- lib/mini_magick/image/info.rb
The following warnings have been suppressed
```
warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
> suppress warning to ambiguous argument

- lib/mini_magick/shell.rb
- spec/lib/mini_magick/shell_spec.rb
For some reasons, stderr is blank. See https://github.com/minimagick/minimagick/issues/471 
This PR adds status to exception for more informative errors, It may help to understand the reason why cmd fails.
> Add cmd status to exception

- README.md
- lib/mini_magick/configuration.rb
- lib/mini_magick/utilities.rb
- spec/lib/mini_magick/image_spec.rb
Add configuration to change temporary directory.
Example:
```ruby
MiniMagick.configure do |config|
config.tmpdir = File.join(Dir.tmpdir, "/my/new/tmp_dir")
end
```
Defaults to `Dir.tmpdir`.
> Add configuration to change temporary directory

- lib/mini_magick/image.rb
- spec/lib/mini_magick/image_spec.rb
**Background**
In `MiniMagick::Image#format`, temporary file were left behind when convert failed.
**Solution**
Fixed to delete unnecessary temporary file when convert fails.
> Fix handling of tempfile in `MiniMagick::Image#format`

- README.md
I wanted to kick off a conversation about removing the recommendation to use `posix-spawn` for Ruby > 2.2. 
It's my understanding that `posix-spawn` is not beneficial after Ruby 2.2, https://github.com/luanzeba/progeny/commit/00dac130925b98f2c2e55adb600385a88a8a4d58 summarizes it well, but at a hight level, when posix-spawn is not specified, [minimagick will use Open3](https://github.com/minimagick/minimagick/blob/2a4d0fc5be414017b084628512c38c2ca2f845c5/lib/mini_magick/configuration.rb#L96). Open3 uses [spawn](https://github.com/ruby/open3/blob/b8909222051b4103a19eba19506727faece252e7/lib/open3.rb#L534) internally, which was [updated in Ruby 2.2](https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/).
Additionally, it seems like `posix-spawn` performs worse than native Ruby …
> No longer recommend posix-spawn for Ruby >= 2.2

- README.md
- lib/mini_magick/configuration.rb
- lib/mini_magick/image.rb
- spec/lib/mini_magick/tool_spec.rb
```
codespell **/*.rb **/*.md -w
```
---
Hello, I was here for minimagick/minimagick@763edb3d45bc76b2fffe2ea47bd2d17ac5cd704a and I took the opportunity to run `codespell` on the codebase
> Fix typos in specs, comments, and readme

- .github/workflows/ci.yml
Workflows run with extended set of permissions by default. By specifying any permission explicitly, all others are set to none.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
> Also add explicit permissions to workflows

- mini_magick.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/mini_magick which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
> Provide a 'Changelog' link on rubygems.org/gems/mini_magick

- lib/mini_magick/configuration.rb
- lib/mini_magick/shell.rb
- spec/lib/mini_magick/shell_spec.rb
Adds support for setting `LD_PRELOAD` specifically for ImageMagick calls plus any other env a user might want to set for ImageMagick but not the whole system.
See #7882
Thanks =)
> Add cli_env option to configure extra env vars for every CLI command

- README.md
- lib/mini_magick/configuration.rb
- lib/mini_magick/shell.rb
- spec/lib/mini_magick/shell_spec.rb
- spec/spec_helper.rb
Allows configuring Open3 to not pass in all other environment variables when making ImageMagick calls, to defend against any vulnerability that may appear in ImageMagick from gaining access to secret values in system env.
This requires explicitly passing in HOME, PATH, and LANG since ImageMagick needs those, and it builds upon the cli_env option.
Idea from: https://github.com/minimagick/minimagick/pull/449#issuecomment-378204956
Thanks for taking a look ☺️
> Add restricted_env option to use Open3 `unsetenv_others:true`

- lib/mini_magick/tool.rb
When running in verbose mode:
```
mini_magick-5.1.2/lib/mini_magick/tool.rb:127: warning: ambiguous `*` has been interpreted as an argument prefix
```
> Fix "ambiguous `*` has been interpreted as an argument prefix" warning

- spec/lib/mini_magick/shell_spec.rb
I am the maintainer of the Debian package of MiniMagick.
https://tracker.debian.org/pkg/ruby-mini-magick
This pull request mirrors a local patch I am using to fix the error message in #590.
> Fix testing with current versions of ImageMagick

- lib/mini_magick/shell.rb
- mini_magick.gemspec
The following code is equivalent and works since Ruby 2.1
> Drop `benchmark` dependency

- lib/mini_magick/tool.rb
- spec/lib/mini_magick/tool_spec.rb
`MiniMagick.compare(errors: false)` is erroring with `wrong number of arguments (given 2, expected 1) (ArgumentError)`
This appears to be due to MiniMagick::Tool.new not explicitly accepting kwargs, so it attempts to instantiate using two positonal args, which is not allowed.
This PR attempts to resolve the issue by updating the method signature of `MiniMagick::Tool.new` to accept kwargs.
> Fix option forwarding in MiniMagick::Tool.new
